### ISSUE TITLE
调研适配 Android 8.0

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/android-sdk-all#104]
https://forum.leancloud.cn/t/android8-0-8-1-pushservice-crash/16463

遇到问题：
1.最新版 Android8.0/8.1未适配新的通知新特性变更,导致targetSdkVersion>=26时,推送消息可达,但无法展示出通知.
2.在 google pixel (原生 android8.0)手机上,当 app 按 home 键或者 back 按键退出 app ,过1-10分钟后,由于 pushservice异常 destroy, 然后 pushservice 自动唤醒失败,导致应用crash 崩溃(致命)。

**Comment by jwfing** [comment]
@BinaryHB 这是你复现过了的问题吗？

**Comment by BinaryHB** [comment]
是的。可以下个 Pixel 模拟器搭载 8.0 系统，1、2 问题都可以稳定复现。

**Comment by jwfing** [comment]
我已经改过来了，明天给你测试一下吧。
