### ISSUE TITLE
收到服务端下发的预期之外的消息不应 crash

### ISSUE THREAD

**Issue by leeyeh** [leancloud/android-sdk-all#111]
https://github.com/leancloud/avoscloud-push/issues/1567#issuecomment-344155443

**Comment by jwfing** [comment]
重复了（ leancloud/android-sdk-all#105 ），且这个 bug 已经在昨天发布的版本中 fix 了。因为老版本也会长时间存在，所以 server 端还是应该通过 config 来区分。
