### ISSUE TITLE
是不是不支持 gradle 3.0.0 ？

### ISSUE THREAD

**Issue by Wing-Li** [leancloud/android-sdk-all#136]
不论怎么配置都报这个错误。

![](https://user-images.githubusercontent.com/12133489/33983667-fc3437ce-e0ef-11e7-834e-e494943f315f.png)

**Comment by jwfing** [comment]
这个需要修改一下本地的 gradle 配置文件，因为我们项目组通用的 gradle 版本没有升级，所以你会遇到这个问题。你本地修改之后，保持不变就可以了。

**Comment by Wing-Li** [comment]
@jwfing 
修改本地 gradle 的什么？
版本号？
支持哪个版本？
