### ISSUE TITLE
Android 8 java.lang.IllegalStateException: Not allowed to start service Intent com.avos.avoscloud.PushService.onDestroy(PushService.java:225)

### ISSUE THREAD

**Issue by codetalks-new** [leancloud/android-sdk-all#145]
报错设备:  Android 8.0 模拟器
估计是因为 Android 8.0 已经加强对后台启动进程的限制了.

> java.lang.RuntimeException:Unable to stop service com.avos.avoscloud.PushService@206a784: java.lang.IllegalStateException: Not allowed to start service Intent { flg=0x10000000 cmp=com.xypuke.texaspoker/com.avos.avoscloud.PushService }: app is in background uid UidRecord{fe72679 u0a86 SVC bg:+1m0s18ms idle procs:2 seq(0,0,0)}
--
2 android.app.ActivityThread.handleStopService(ActivityThread.java:3587)
3 ......
4 Caused by:
5 java.lang.IllegalStateException:Not allowed to start service Intent { flg=0x10000000 cmp=com.xypuke.texaspoker/com.avos.avoscloud.PushService }: app is in background uid UidRecord{fe72679 u0a86 SVC bg:+1m0s18ms idle procs:2 seq(0,0,0)}
6 android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
7 android.app.ContextImpl.startService(ContextImpl.java:1461)
8 android.content.ContextWrapper.startService(ContextWrapper.java:644)
9 com.avos.avoscloud.PushService.onDestroy(PushService.java:225)
10 android.app.ActivityThread.handleStopService(ActivityThread.java:3569)
11 android.app.ActivityThread.-wrap26(Unknown Source:0)
12 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
13 android.os.Handler.dispatchMessage(Handler.java:105)
14 android.os.Looper.loop(Looper.java:164)
15 android.app.ActivityThread.main(ActivityThread.java:6541)
16 java.lang.reflect.Method.invoke(Native Method)
17 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by jwfing** [comment]
你是最新版本吗？

**Comment by codetalks-new** [comment]
上面报错时是 4.5.1 我更新一下SDK试试.

**Comment by jwfing** [comment]
嗯，你更新一下版本吧，新版本是适配了 Android 8.0 的。
