### ISSUE TITLE
下载的文件里没有 avoscloud.jar 等jar文件

### ISSUE THREAD

**Issue by saidemarlin** [leancloud/android-sdk-all#152]
下载的文件里没有 avoscloud.jar 等jar文件，只有 
fastjson-1.2.30 ；
Java-WebSocket-1.3.2-leancloud；
okhttp-3.8.0；
okio-1.13.0；
protobuf-java-3.4.0；
qq.sdk.1.6.1；
weibo.sdk.android.sso.3.0.1-leancloud这几个jar文件， 其他的jar文件在哪里？

**Comment by saidemarlin** [comment]
直接用Gradle解决了。

**Comment by jwfing** [comment]
是的，我们现在直接提供源码，大家本地 build 即可。
