### ISSUE TITLE
v4.6.2 AVCloud.setProductionMode(false); 不生效

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/android-sdk-all#166]
来源：https://leanticket.cn/tickets/15702

问题：v4.6.2 AVCloud.setProductionMode(false); 无法调用云引擎预备环境，会继续调用生产环境
v3.16.4 表现正常。

复现 demo：
[Test.zip](https://github.com/leancloud/android-sdk-all/files/1663230/Test.zip)

**Comment by jwfing** [comment]
@BinaryHB AVCloud.setProductionMode 只对在 android app 里面调用云函数有影响，这个标志设置与否，不影响 AVObject 的 save 的。
现在究竟是 AVObject 保存失败，还是 android app 中云函数调用失败？
