### ISSUE TITLE
编译Android SDK时报错

### ISSUE THREAD

**Issue by wangzhenhua92429** [leancloud/android-sdk-all#188]
编译过程：从github上clone了项目，然后导入Android studio后在terminal里执行./gradlew build后报
Execution failed for task ':avoscloud-push:testDebugUnitTest'.
请问这个怎么解决

**Comment by jwfing** [comment]
你在命令行通过 build-sdk.sh 来编译呢？
注意把 build-sdk.sh 文件中第23行：
```
L23 gradle clean assemble uploadArchives
```
改成
```
gradle clean assemble
```

**Comment by wangzhenhua92429** [comment]
@jwfing 也是不行啊，没生成任何东西

**Comment by jwfing** [comment]
编译没报错就会生成 library package，注意查看 target 目录。
