### ISSUE TITLE
Performance Issue in AVIMConversationsQuery which will lead UI block

### ISSUE THREAD

**Issue by liaohuqiu** [leancloud/android-sdk-all#19]
https://github.com/leancloud/android-sdk-all/blob/0ecdd74ac94892df3edb742ecf03265d68b4633d/avoscloud-push/src/main/java/com/avos/avoscloud/im/v2/AVIMConversationsQuery.java#L529

We use LeanCloud a lot and detected there are some performance issue.

`onReceive` will run in Main Thread.  Currently it did too much work:

1. `parseQueryResult` deserialize the data, when we query a conversation for the first time, it will take a lot of time.

2. `insertConversations` operate the DB.

**Comment by BinaryHB** [comment]
收到，正在看。

**Comment by liaohuqiu** [comment]
Anything update?
