### ISSUE TITLE
意见反馈组件相关问题

### ISSUE THREAD

**Issue by ghost** [leancloud/android-sdk-all#199]
1，如果只是想接入意见反馈这一个组件，请问怎么收费？
2，Android端下载了意见反馈的移动app[http://download.leancloud.cn/apk/AVOSCloudMobileApp.apk](url)  根本登录不上去。提示网络异常!是不是已经停止维护了？

**Comment by jwfing** [comment]
@fcscr126608 
1. 意见反馈组件按照存储 API 来收费。
2. LeanCloud 移动端已经下架了。
