### ISSUE TITLE
客户端在查询云端已删除或者已过期的会话时需要抛错

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/android-sdk-all#200]
来源：https://leanticket.cn/tickets/17727

### 问题详情
云端会自动删除 1 年不活跃的会话，同时我们也提供了删除会话的 API。这样就会出现客户端通过缓存，去拉取服务器已经不存在会话的状态。

#### 使用 fetchInfoInBackground
概括：拿一个本地已缓存但云端已删除的 conversation 去 fetchInfoInBackground，服务端返回 list 为空。

期望：客户端抛出一个 exception，明确指示该会话已不存在。

改进：SDK 加一层判断，在这种情况下抛出[这里](https://github.com/leancloud/paas/wiki/RTM-客户端-Error-清单（draft）#91xx)的 9100 错误码和对应的错误信息。

**Comment by jwfing** [comment]
@BinaryHB 我测试 第二种情况是不会抛出 IndexOutOfBoundsException 的啊，只是 list 为 null 而已。

**Comment by jwfing** [comment]
第一个问题已经 fix 了，第二个问题我这边确认不存在，可能的话我跑跑你的测试代码吧 @BinaryHB
