### ISSUE TITLE
crash in some device when  AVOSCloud.initialize

### ISSUE THREAD

**Issue by kingty** [leancloud/android-sdk-all#211]
11-19 16:43:28.183: E/AndroidRuntime(7711): FATAL EXCEPTION: main
11-19 16:43:28.183: E/AndroidRuntime(7711): java.lang.NoClassDefFoundError: com.alibaba.fastjson.JSON
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at com.avos.avoscloud.AVOSCloud.<clinit>(AVOSCloud.java:102)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at com.tantan.build.core.App.onCreate(App.kt:25)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.app.ActivityThread.access$1600(ActivityThread.java:148)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.os.Looper.loop(Looper.java:137)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at android.app.ActivityThread.main(ActivityThread.java:5473)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at java.lang.reflect.Method.invoke(Method.java:525)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
11-19 16:43:28.183: E/AndroidRuntime(7711): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by kingty** [comment]
？？

**Comment by weakish** [comment]
@kingty 可以试下新版（4.7.9），看看是否正常。如果问题仍然存在，请提供详细信息，包括 SDK 版本号、gradle 文件、具体的触发报错的 `AVOSCloud.initialize` 代码等。
