### ISSUE TITLE
onConnectionPaused / onConnectionResume 触发时间过慢

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/android-sdk-all#47]
https://leanticket.cn/tickets/13753

这 2 个回调在网络缓慢的情况下，触发特别滞后，甚至要等待 2 分钟之久。这个问题本质上是因为 onConnectionPaused / onConnectionResume 的设计问题，他们的触发条件是一个 3 分钟的心跳成功与否才触发。

建议有一个超时时间，比如 15 秒，不管网络是什么情况，超时了就自然触发。

**Comment by jwfing** [comment]
这个工单算不算被我说服了。。。

**Comment by BinaryHB** [comment]
最后我补了一刀，主要用户觉得不好向他们的测试同事解释这个事情。
