### ISSUE TITLE
v4.4.6 编译通不过

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/android-sdk-all#51]
https://leanticket.cn/tickets/13744

报错：transformClassesWithJarMergingForDebug

有可能是我们 SDK 内部的引用重复了

**Comment by daweibayu** [comment]
https://github.com/leancloud/android-sdk-all/pull/50 做了一些修改，新发布的 4.4.7 已经没有问题了。但是还不确定是不是这些资源文件引起的。
