### ISSUE TITLE
升级华为推送服务

### ISSUE THREAD

**Issue by jwfing** [leancloud/android-sdk-all#57]
@daweibayu 来补充一下现状和问题吧。

**Comment by daweibayu** [comment]
具体文档可以参考 http://developer.huawei.com/consumer/cn/service/hms/developer.html 。
他们的 qq 群 496337128。
升级时遇到的问题主要是对于“华为移动服务” app 的依赖，如果app 版本没有更新到对应的版本或者旧华为手机上根本就没有此服务，则会造成 connect 失败，直接导致服务不可用。

**Comment by nicecui** [comment]
https://leanticket.cn/tickets/14725
@jwfing 再去调查下看看进展，看能不能升级下

**Comment by jwfing** [comment]
ref:
- leancloud/uluru-platform#3817
- leancloud/uluru-platform#3459
