### ISSUE TITLE
支持二进制消息类型

### ISSUE THREAD

**Issue by jwfing** [leancloud/android-sdk-all#77]
ref: leancloud/paas#951

**Comment by jwfing** [comment]
check list:
- [x] send binary message;
- [x] recv binary message;
- [x] recv unread binary message;
- [x] update binary message;
- [x] recall binary message;
- [x] save binary message into local storage.

**Comment by leeyeh** [comment]
补充两点：

- [x] unread last message
- [x] conv query with last message
